In [25]:
# Credit: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-download-beginner-blitz-tensor-tutorial-py

In [26]:
# For python2/3 compatibility
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

In [27]:
%matplotlib inline
import numpy as np
import torch
import matplotlib.pyplot as plt

# Getting Started

## Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

Construct a randomly initialized matrix:



In [28]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2986, 0.9961, 0.1173],
        [0.3160, 0.0526, 0.6780],
        [0.7607, 0.4185, 0.7726],
        [0.2782, 0.2703, 0.2168],
        [0.7099, 0.1715, 0.5292]])


In [29]:
x.dtype

torch.float32

In [31]:
x.size()

torch.Size([5, 3])

Construct a matrix filled zeros and of dtype long:



In [32]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [35]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [34]:
x = torch.tensor([[1,2], [3,4]])
print(x)

tensor([[1, 2],
        [3, 4]])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [36]:
x = x.new_tensor([2, 4])                      # inherit its size (shape) and dtype
print(x)
print(x.dtype)

x = torch.ones([5, 3], dtype=torch.int)
print(x)
x = torch.randn_like(x, dtype=torch.float)    # override dtype
print(x)                                      # result has the same size

tensor([2., 4.])
torch.float32
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[-1.5228,  0.9799,  0.8282],
        [ 0.6001,  0.7433, -1.2898],
        [-0.3279,  0.8509,  0.4074],
        [ 0.8735, -0.9321, -1.3161],
        [-1.1103, -0.0507, -0.7092]])


Get its size:



In [38]:
print(x.size()[1])

3


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

## Operations
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [40]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-1.3998,  1.7313,  1.4620],
        [ 1.4603,  1.3029, -0.7805],
        [-0.1730,  1.5596,  0.9993],
        [ 1.3617, -0.6545, -0.6751],
        [-0.3848,  0.8102, -0.5544]])


Addition: syntax 2



In [41]:
print(torch.add(x, y))

tensor([[-1.3998,  1.7313,  1.4620],
        [ 1.4603,  1.3029, -0.7805],
        [-0.1730,  1.5596,  0.9993],
        [ 1.3617, -0.6545, -0.6751],
        [-0.3848,  0.8102, -0.5544]])


Addition: in-place



In [42]:
# adds x to y
y.add_(x)
print(y)

tensor([[-1.3998,  1.7313,  1.4620],
        [ 1.4603,  1.3029, -0.7805],
        [-0.1730,  1.5596,  0.9993],
        [ 1.3617, -0.6545, -0.6751],
        [-0.3848,  0.8102, -0.5544]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [46]:
print(x[:, 1])

tensor([ 0.9799,  0.7433,  0.8509, -0.9321, -0.0507])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [48]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [50]:
x.t()

tensor([[-1.8927, -0.9411,  0.0260,  1.0107],
        [ 0.6511, -2.2246,  0.7126, -1.8753],
        [-0.7039,  1.2022, -2.3297,  0.1043],
        [-1.0270, -0.9857,  0.6816, -0.3370]])

If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [51]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0359])
0.0359316840768


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array



In [52]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [53]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [21]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([-0.4194], device='cuda:0')
tensor([-0.4194], dtype=torch.float64)


In [22]:
# more simply
if torch.cuda.is_available():        
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.cuda()                           # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.cpu())                         # ``.to`` can also change dtype together!

tensor([-0.4194], device='cuda:0')
tensor([-0.4194])



Autograd: automatic differentiation
===================================

Central to all neural networks in PyTorch is the ``autograd`` package.
Let’s first briefly visit this, and we will then go to training our
first neural network.


The ``autograd`` package provides automatic differentiation for all operations
on Tensors. It is a define-by-run framework, which means that your backprop is
defined by how your code is run, and that every single iteration can be
different.

Let us see this in more simple terms with some examples.

Tensor
--------

``torch.Tensor`` is the central class of the package. If you set its attribute
``.requires_grad`` as ``True``, it starts to track all operations on it. When
you finish your computation you can call ``.backward()`` and have all the
gradients computed automatically. The gradient for this tensor will be
accumulated into ``.grad`` attribute.

To stop a tensor from tracking history, you can call ``.detach()`` to detach
it from the computation history, and to prevent future computation from being
tracked.

To prevent tracking history (and using memory), you can also wrap the code block
in ``with torch.no_grad():``. This can be particularly helpful when evaluating a
model because the model may have trainable parameters with `requires_grad=True`,
but for which we don't need the gradients.

There’s one more class which is very important for autograd
implementation - a ``Function``.

``Tensor`` and ``Function`` are interconnected and build up an acyclic
graph, that encodes a complete history of computation. Each tensor has
a ``.grad_fn`` attribute that references a ``Function`` that has created
the ``Tensor`` (except for Tensors created by the user - their
``grad_fn is None``).

If you want to compute the derivatives, you can call ``.backward()`` on
a ``Tensor``. If ``Tensor`` is a scalar (i.e. it holds a one element
data), you don’t need to specify any arguments to ``backward()``,
however if it has more elements, you need to specify a ``gradient``
argument that is a tensor of matching shape.



Create a tensor and set requires_grad=True to track computation with it



In [54]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


Do an operation of tensor:



In [55]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


``y`` was created as a result of an operation, so it has a ``grad_fn``.



In [56]:
print(y.grad_fn)

Do more operations on y



In [57]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


``.requires_grad_( ... )`` changes an existing Tensor's ``requires_grad``
flag in-place. The input flag defaults to ``False`` if not given.



In [58]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


Gradients
---------
Let's backprop now
Because ``out`` contains a single scalar, ``out.backward()`` is
equivalent to ``out.backward(torch.tensor(1))``.



In [59]:
out.backward()

print gradients d(out)/dx




In [60]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


You should have got a matrix of ``4.5``. Let’s call the ``out``
*Tensor* “$o$”.
We have that $o = \frac{1}{4}\sum_i z_i$,
$z_i = 3(x_i+2)^2$ and $z_i\bigr\rvert_{x_i=1} = 27$.
Therefore,
$\frac{\partial o}{\partial x_i} = \frac{3}{2}(x_i+2)$, hence
$\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{9}{2} = 4.5$.



You can do many crazy things with autograd!



In [62]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-1103.8849, -1158.7416,  -579.3843], grad_fn=<MulBackward>)


In [56]:
y.data

tensor([1195.3351,  574.4010,   85.1459])

In [48]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)

print(x.grad)

tensor([ 102.4000, 1024.0000,    0.1024])


You can also stop autograd from tracking history on Tensors
with ``.requires_grad``=True by wrapping the code block in
``with torch.no_grad():``



In [49]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
	print((x ** 2).requires_grad)

True
True
False


**Read Later:**

Documentation of ``autograd`` and ``Function`` is at
http://pytorch.org/docs/autograd

